import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalize } from "../../src/crypto/canonicalJson.js";
import { hex, sha256 } from "../../src/crypto/hash.js";
import { verifyBundle } from "../../src/crypto/verifyBundle.js";
import type { RecordBundle } from "../../src/types.js";

/**
 * Cross-implementation drift check: `fixtures/vectors.json` was generated by
 * `scripts/generate-vectors.ts` using `packages/db`'s real, production crypto code — not
 * a hand-typed fixture. If this SDK's independently ported `canonicalize`/`sha256`/
 * `verifyBundle` don't reproduce the exact same output the server produced, agent
 * signatures made with this SDK will fail to verify against a real server. Re-run
 * `pnpm generate:vectors` after any protocol or crypto change and commit the result.
 */

interface Vectors {
  canonicalization: { input: unknown; expected: string; expectedHex?: string }[];
  validBundle: RecordBundle;
  tamperedBundle: RecordBundle;
}

const vectors: Vectors = JSON.parse(readFileSync(new URL("../../fixtures/vectors.json", import.meta.url), "utf8"));

describe("cross-implementation vectors (generated from packages/db)", () => {
  it("canonicalize() matches the server's output byte-for-byte", () => {
    for (const v of vectors.canonicalization) {
      expect(canonicalize(v.input)).toBe(v.expected);
      if (v.expectedHex) expect(hex(sha256(Buffer.from(canonicalize(v.input), "utf8")))).toBe(v.expectedHex);
    }
  });

  it("verifyBundle() accepts a bundle genuinely signed by the server's crypto code", () => {
    const result = verifyBundle(vectors.validBundle, vectors.validBundle.platformKeys);
    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });

  it("verifyBundle() rejects a bundle tampered with after signing", () => {
    const result = verifyBundle(vectors.tamperedBundle, vectors.tamperedBundle.platformKeys);
    expect(result.valid).toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
    // The offer was tampered, so re-deriving its hash must disagree with the accept's
    // recorded offerHash and the genesis hash — this is the canary that verifyBundle
    // actually re-derives hashes rather than trusting the bundle's own claims.
    expect(result.errors.map((e) => e.code)).toEqual(expect.arrayContaining(["offer_hash", "genesis_hash"]));
  });
});
