"""RFC 8785 JSON Canonicalization Scheme (JCS), ported from
``packages/db/src/crypto/canonicalJson.ts``. The two MUST stay byte-for-byte identical,
or agent signatures made with this SDK will fail to verify against a real OpenGlass
server. ``tests/crypto/test_vectors.py`` checks this port against vectors generated by
the server's own (JavaScript) implementation — see that file before touching this one.

The one genuinely hard part of a cross-language JCS port is number formatting: JCS
mandates ECMAScript's ``Number::toString``, which Python's ``repr``/``json`` module does
not produce by default (different thresholds for switching to exponential notation,
different exponent formatting). ``_format_number`` below reformats Python's own
shortest-round-trip digit sequence (which *is* the same class of algorithm V8 uses, so
the digits themselves already match) according to ECMAScript's presentation rules.
"""

from __future__ import annotations

import math
import re

_EXP_RE = re.compile(r"^(-?)(\d+)(?:\.(\d+))?[eE]([+-]?\d+)$")
_PLAIN_RE = re.compile(r"^(-?)(\d+)(?:\.(\d+))?$")


def _format_number(value: float | int) -> str:
    if isinstance(value, bool):  # bool is a subclass of int; canonicalize() dispatches around this
        raise TypeError("booleans are not numbers")
    if isinstance(value, int):
        return str(value)
    if not math.isfinite(value):
        raise ValueError(f"JCS: non-finite number {value!r}")
    if value == 0:
        return "0"  # covers -0.0 -> "0", matching JS

    negative = value < 0
    r = repr(-value if negative else value)

    m = _EXP_RE.match(r)
    if m:
        _, int_part, frac_part, exp_str = m.groups()
        exp = int(exp_str)
    else:
        m = _PLAIN_RE.match(r)
        assert m is not None, f"unexpected float repr: {r!r}"
        _, int_part, frac_part = m.groups()
        exp = 0
    frac_part = frac_part or ""

    combined = int_part + frac_part
    point_pos = len(int_part) + exp  # decimal point sits after this many chars of `combined`

    stripped = combined.rstrip("0") or "0"
    digits = stripped.lstrip("0") or "0"
    k = len(digits)
    n = point_pos - len(stripped) + k

    if k <= n <= 21:
        out = digits + "0" * (n - k)
    elif 0 < n <= 21:
        out = digits[:n] + "." + digits[n:]
    elif -6 < n <= 0:
        out = "0." + "0" * (-n) + digits
    else:
        mantissa = digits[0] + ("." + digits[1:] if k > 1 else "")
        e = n - 1
        out = f"{mantissa}e{'+' if e >= 0 else '-'}{abs(e)}"

    return f"-{out}" if negative else out


_ESCAPES = {
    '"': '\\"',
    "\\": "\\\\",
    "\b": "\\b",
    "\f": "\\f",
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def _format_string(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch in _ESCAPES:
            out.append(_ESCAPES[ch])
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)  # non-ASCII (including astral-plane) passed through literally, matching JSON.stringify
    out.append('"')
    return "".join(out)


def canonicalize(value: object) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return _format_string(value)
    if isinstance(value, (int, float)):
        return _format_number(value)
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(canonicalize(v) for v in value) + "]"
    if isinstance(value, dict):
        # JS's `canonicalize` omits object properties whose value is `undefined`. Python
        # has no equivalent of "key present but undefined" — a dict simply doesn't have
        # the key — so the same discipline applies: build dicts without keys you want
        # omitted, rather than setting a key to `None` and expecting it to be dropped
        # (`None` canonicalizes to `"null"`, matching JS's treatment of an explicit `null`).
        keys = sorted(value.keys(), key=_utf16_sort_key)
        return "{" + ",".join(f"{_format_string(k)}:{canonicalize(value[k])}" for k in keys) + "}"
    raise TypeError(f"JCS: unsupported value of type {type(value).__name__}")


def _utf16_sort_key(s: str) -> bytes:
    """JCS sorts object keys by UTF-16 code unit order (JS's default string `<`), not
    Unicode code point order — these agree for every BMP character but diverge for
    astral-plane characters (surrogate pairs sort differently than their code point
    would). Encoding to UTF-16BE and comparing bytes reproduces JS's exact ordering."""
    return s.encode("utf-16-be", "surrogatepass")


def canonicalize_to_bytes(value: object) -> bytes:
    return canonicalize(value).encode("utf-8")
